---

- name: install and run service
  hosts: localhost
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present

    - name: Start service
      service:
        name: nginx
        state: started
        enabled: true
~                     


If we wanted to check the yml file is correct or not we can user below command.
ansible-playbook --syntax-check <filenam>.yml ex. nginx.tml
